"""Build clean, human-usable field maps from the raw extraction.

Filters out structural/barcode noise and keeps only fillable leaf fields
(/Tx text, /Btn buttons & checkboxes, /Ch choice/dropdown) for I-589, I-821, G-1450.

Usage: python scripts/build_clean_map.py
Output: assets/field-maps/<form>.clean.txt  and  docs/04-field-maps.md
"""
import os
import re

OUT_DIR = "assets/field-maps"
TARGETS = ["i-589", "i-821", "g-1450", "i-765", "g-28"]

NOISE = re.compile(r"(PDF417BarCode|#pageSet|CurrentPage|PageCount)\b", re.IGNORECASE)
LEAF = re.compile(r"^(/Tx|/Btn|/Ch)\s+\|\s+(.+)$")


def clean(form):
    src = os.path.join(OUT_DIR, f"{form}.acro.txt")
    if not os.path.exists(src):
        return []
    rows = []
    with open(src, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            m = LEAF.match(line)
            if not m:
                continue
            ftype, name = m.group(1), m.group(2)
            if NOISE.search(name):
                continue
            rows.append((ftype, name))
    out = os.path.join(OUT_DIR, f"{form}.clean.txt")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(f"{t:5} | {n}" for t, n in rows))
    return rows


def short(name):
    # last meaningful segment for readability
    seg = name.split(".")[-1]
    return re.sub(r"\[\d+\]$", "", seg)


def main():
    md = ["# Real Extracted AcroForm Field Maps",
          "",
          "> Auto-generated by `scripts/build_clean_map.py` from the live USCIS PDFs.",
          "> These are the **fully-qualified AcroForm field names** to use when filling.",
          "> Forms are hybrid XFA — see `docs/05-pdf-fill-strategy.md` for the fill approach.",
          ""]
    for form in TARGETS:
        rows = clean(form)
        if not rows:
            continue
        md.append(f"## {form.upper()}  ({len(rows)} fillable fields)")
        md.append("")
        md.append("| Type | Short name | Fully-qualified field name |")
        md.append("|---|---|---|")
        for t, n in rows[:60]:
            md.append(f"| {t} | {short(n)} | `{n}` |")
        if len(rows) > 60:
            md.append(f"| ... | ... | _+{len(rows) - 60} more in_ `assets/field-maps/{form}.clean.txt` |")
        md.append("")
        print(f"{form:8} -> {len(rows)} clean fields")
    with open("docs/04-field-maps.md", "w", encoding="utf-8") as fh:
        fh.write("\n".join(md))


if __name__ == "__main__":
    main()
