-- Supabase schema for the immigration intake platform.
-- Principles: data minimization, RLS-by-default, attorney-only access to client PII.
-- See docs/02-technical-compliance-blueprint.md (Section B).

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------
create type case_status as enum (
  'intake',
  'evidence_review',
  'flagged_for_review',
  'ready_to_file',
  'completed'
);

create type document_type as enum (
  'passport',
  'police_report',
  'medical',
  'ticket',
  'political_membership',
  'other'
);

-- ---------------------------------------------------------------------------
-- Attorneys (mirror of auth.users for role + assignment)
-- ---------------------------------------------------------------------------
create table attorneys (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null,
  bar_number text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Clients (intake originates from WhatsApp)
-- Minimize PII: store only what maps to USCIS forms.
-- ---------------------------------------------------------------------------
create table clients (
  id uuid primary key default gen_random_uuid(),
  phone_number text unique not null,           -- WhatsApp identifier
  language text not null default 'es',
  consented_at timestamptz,                    -- disclaimer + sensitive-data opt-in timestamp
  assigned_attorney uuid references attorneys (id),
  status case_status not null default 'intake',
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Case files
-- structured_data holds only the fields needed to fill I-589 / I-821.
-- ---------------------------------------------------------------------------
create table case_files (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references clients (id) on delete cascade,
  form_type text not null default 'I-589',     -- 'I-589' | 'I-821'
  structured_data jsonb not null default '{}',
  narrative_summary text,
  last_entry_date date,                        -- drives one-year asylum deadline calc
  status case_status not null default 'intake',
  generated_pdf_path text,                     -- private Storage object path (signed-URL access)
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Evidence (Mistake Vault writes anomaly_flags)
-- ---------------------------------------------------------------------------
create table evidence (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references case_files (id) on delete cascade,
  document_type document_type not null default 'other',
  storage_path text not null,                  -- private bucket object path
  raw_text text,                               -- OCR + translation
  anomaly_flags jsonb,                         -- output of Mistake Vault agent
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Deadlines (AAF, one-year filing) -> WhatsApp reminders
-- ---------------------------------------------------------------------------
create table deadlines (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references case_files (id) on delete cascade,
  kind text not null,                          -- 'annual_asylum_fee' | 'one_year_filing'
  due_date date not null,
  notified_at timestamptz,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Audit log (NY SHIELD-aligned access trail)
-- ---------------------------------------------------------------------------
create table audit_log (
  id bigint generated by default as identity primary key,
  actor uuid references attorneys (id),
  action text not null,
  target_table text,
  target_id uuid,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
alter table attorneys enable row level security;
alter table clients enable row level security;
alter table case_files enable row level security;
alter table evidence enable row level security;
alter table deadlines enable row level security;
alter table audit_log enable row level security;

-- Attorneys can read their own row.
create policy "attorney reads self" on attorneys
  for select using (id = auth.uid());

-- An attorney can only see clients assigned to them.
create policy "attorney reads assigned clients" on clients
  for select using (assigned_attorney = auth.uid());
create policy "attorney updates assigned clients" on clients
  for update using (assigned_attorney = auth.uid());

-- Case files visible only for assigned clients.
create policy "attorney reads assigned cases" on case_files
  for select using (
    exists (
      select 1 from clients c
      where c.id = case_files.client_id and c.assigned_attorney = auth.uid()
    )
  );
create policy "attorney updates assigned cases" on case_files
  for update using (
    exists (
      select 1 from clients c
      where c.id = case_files.client_id and c.assigned_attorney = auth.uid()
    )
  );

-- Evidence visible only for assigned cases.
create policy "attorney reads assigned evidence" on evidence
  for select using (
    exists (
      select 1 from case_files cf
      join clients c on c.id = cf.client_id
      where cf.id = evidence.case_id and c.assigned_attorney = auth.uid()
    )
  );

-- Deadlines visible only for assigned cases.
create policy "attorney reads assigned deadlines" on deadlines
  for select using (
    exists (
      select 1 from case_files cf
      join clients c on c.id = cf.client_id
      where cf.id = deadlines.case_id and c.assigned_attorney = auth.uid()
    )
  );

-- NOTE: The WhatsApp webhook / agents run with the service-role key (bypasses RLS)
-- on the server only. Never expose the service-role key to the browser.
